### ISSUE TITLE
Progress Bar Issue in St terminal

### ISSUE THREAD

**Issue by athuld** [Akianonymus/gdrive-downloader#17]
![pic-selected-201218-0134-12](https://user-images.githubusercontent.com/74203601/102537647-35ce7f00-40d1-11eb-8b44-c2eeecb0f45c.png)

**Comment by athuld** [comment]
It should be in 2 lines only right

**Comment by Akianonymus** [comment]
Do following command ans give output

```
echo "${TERM}"

```

Check if your terminal supports ansi escapes.

**Comment by athul05** [comment]
> Do following command ans give output
> 
> ```
> echo "${TERM}"
> ```
> 
> Check if your terminal supports ansi escapes.

![image](https://user-images.githubusercontent.com/58630991/103136548-5907b880-46e7-11eb-97e0-d4c5fa789acf.png)

**Comment by athuld** [comment]
> Do following command ans give output
> 
> ```
> echo "${TERM}"
> ```
> 
> Check if your terminal supports ansi escapes.

![image](https://user-images.githubusercontent.com/74203601/103136567-818fb280-46e7-11eb-8dac-ea83f0b2a0bc.png)

**Comment by Akianonymus** [comment]
@athuld Hmm, will push a fix soon.

**Comment by athuld** [comment]
> @athuld Hmm, will push a fix soon.

The weird thing is that  in a tmux session , the progress bar is absolutely fine

**Comment by Akianonymus** [comment]
@athuld Well, the script tries to detect the terminal type, if a specified terminal is given, then progress bar is properly shown.

You current terminal ( st ) is not currently handled, thus breaking the progress bar.

**Comment by athuld** [comment]
Oh okay got it....btw a great thanks for your script ..i've been searching for downloading gdrive folders efficiently for a while now and accidentally stumbled upon your repo... thanks a ton for the awesome work

**Comment by Akianonymus** [comment]
Pushed the fix, update with `gdl -u` and try again.
