### ISSUE TITLE
When the file in a shared folder exceed the download quota limit, the script will be stuck

### ISSUE THREAD

**Issue by smiliang** [Akianonymus/gdrive-downloader#18]
Hello,

When the script is downloading a shared folder, if a file exists in the folder but exceeds the download quota limit, it will cause the script to get stuck.
Google Drive site returns http code 200 but the content is a page with hints "Google Drive - Quota exceeded". The script will continuously try to test whether the file is in the local directory every 0.5 seconds.

**Comment by Akianonymus** [comment]
I have pushed a fix, try again.

**Comment by Akianonymus** [comment]
Also, if you hit storage qouta limit, see --oauth or --key option.

**Comment by smiliang** [comment]
> I have pushed a fix, try again.

Thank you, problem solved.
I'll try those two options.
