### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by TheLastGimbus** [Akianonymus/gdrive-downloader#19]
I spent about 2 hours looking up like 8 different huge tools, that wanted me to log in, create some api keys, and never worked

AND I JUST WANTED TO DOWNLOAD A PUBLIC LINK

And this just works! Thank you for making this!

**Comment by Akianonymus** [comment]
Haha, same story here. I am glad it helps someone else too.

Offtopic, but I would like to add a point, i am glad i knew only shell then and made it a shell script. Now i can just run it almost everywhere ( non-wsl windows users crying in the corner ).

**Comment by TheLastGimbus** [comment]
> only shell

It took me like 15 minutes to `go get` some skicka shit. (Un)official stuff from google itself (that almost all github actions use)- and it's blocked by **them**

**Comment by Akianonymus** [comment]
@TheLastGimbus They should provide binaries, xD.

**Comment by Akianonymus** [comment]
Closing this.
