### ISSUE TITLE
[Feature request] Background download with links input from a file and detailed logging

### ISSUE THREAD

**Issue by vNa5h** [Akianonymus/gdrive-downloader#21]
Hey can you add support for background downloading with links picked up from a file.
This will be easier to add a cron tab.

Right now I'm using-
nohup gdl -o -q https://drive.google.com/file/d/xxx &
For background downloading with nohup

Also support for logging with bit more details like file name link start time end time..avg speed etc

**Comment by Akianonymus** [comment]
First things first, those are like 2 different features, create individual issues.

Second, I am assuming the logging is only applicable the download is running in bg ? as it doesn't makes sense to output name, link and stuff for foreground downloading

**Comment by vNa5h** [comment]
Yeah for background downloading .. In short to work as a daemon.. Unattended triggered by cronjob picking links from the file

**Comment by vNa5h** [comment]
> First things first, those are like 2 different features, create individual issues.
> 
> Second, I am assuming the logging is only applicable the download is running in bg ? as it doesn't makes sense to output name, link and stuff for foreground downloading

Creating new issue
