### ISSUE TITLE
"Download failed"/"Download incomplete"

### ISSUE THREAD

**Issue by miraodasilva** [Akianonymus/gdrive-downloader#22]
Hi,

First of all, this is a great tool, it helped me download all the contents of the following [drive](https://drive.google.com/drive/folders/1GwXP-KpWOxOenOxITTsURJZQ_1pkd4-j) . Although it downloaded everything fine, it frequently said "Download failed"/"Download incomplete", although the download was completed adequately. Just thought you should know. Maybe you can reproduce it with that link. Thanks in advance.

**Comment by Akianonymus** [comment]
I have fixed the issue, update and try again.

If not fixed, then reopen the issue
