### ISSUE TITLE
Oauth not working

### ISSUE THREAD

**Issue by InnovArul** [Akianonymus/gdrive-downloader#28]
With the new installation of `gdl`, I am facing the following error:
```
/home/arul/.gdrive-downloader/gdl: line 18: 2: Missing string
```
I have executed `gdl` with command: `gdl <gdrive_link> -o`.
It asks for a new account name. After giving the account name, it throws the above error.

`.gdrive-downloader/gdl`:
```
#!/usr/bin/env bash
LAST_UPDATE_TIME="1629023193" # added values
VALUES_LIST="REPO COMMAND_NAME INSTALL_PATH TYPE TYPE_VALUE SHELL_RC LAST_UPDATE_TIME AUTO_UPDATE_INTERVAL INSTALLATION GLOBAL_INSTALL PERM_MODE GDL_INSTALLED_$
REPO="Akianonymus/gdrive-downloader" # added values
COMMAND_NAME="gdl" # added values
INSTALL_PATH="/home/arul/.gdrive-downloader" # added values
TYPE="branch" # added values
TYPE_VALUE="master" # added values
SHELL_RC="/home/arul/.zshrc" # added values
AUTO_UPDATE_INTERVAL="432000" # added values
INSTALLATION="bash" # added values
GLOBAL_INSTALL="false" # added values
PERM_MODE="u" # added values
GDL_INSTALLED_WITH="script" # added values
LATEST_INSTALLED_SHA="17185a7f55fefdea4ed20d3fe13eba315ab02299" # added values
SELF_SOURCE="true"
_assert_regex(){
declare pattern="${1:?Error: Missing pattern}" string="${2:?Missing string}"
if [[ $string =~ $pattern ]];then
return 0
else
return 1
fi
}
```

**Comment by Akianonymus** [comment]
Well, i messed something up, will look into it

**Comment by Akianonymus** [comment]
For now, use this file

https://github.com/Akianonymus/gdrive-downloader/raw/edfa2e5fa656d4eadcc5189b58bfe123dc416ac4/bash/release/gdl

It doesn't have the latest proxy flag, but should work for oauth stuff.

btw, you don't need oauth for public stuff.

**Comment by vNa5h** [comment]
Yeah latest release is broken

**Comment by InnovArul** [comment]
> For now, use this file
> 
> https://github.com/Akianonymus/gdrive-downloader/raw/edfa2e5fa656d4eadcc5189b58bfe123dc416ac4/bash/release/gdl
> 
> It doesn't have the latest proxy flag, but should work for oauth stuff.
> 
> btw, you don't need oauth for public stuff.

Thanks a lot. I was downloading some files that are not public, hence oauth.

**Comment by Akianonymus** [comment]
Hmm. I will try to push a fix asap.

**Comment by Akianonymus** [comment]
I have pushed the fixes, update and try again.

**Comment by vNa5h** [comment]
New errors now

**Comment by Akianonymus** [comment]
@vNa5h Create a issue.
