### ISSUE TITLE
How to put '. /home/$USER/.bashrc' in a sh script

### ISSUE THREAD

**Issue by edwardnguyen1705** [Akianonymus/gdrive-downloader#33]
If I put these two lines in a sh script, then the second line `. /home/$USER/.bashrc` is not executed.
`
curl -Ls --compressed  https://github.com/Akianonymus/gdrive-downloader/raw/master/install.sh | sh -s
. /home/$USER/.bashrc
`
But if I run it in a terminal then it is executed.

**Comment by Akianonymus** [comment]
Umm what, i don't understand.
