### ISSUE TITLE
Support for downloading documents in required formats

### ISSUE THREAD

**Issue by ajohnston9** [Akianonymus/gdrive-downloader#34]
Tried the script on a sample public file I found [here](https://drive.google.com/file/d/1S8gJeCD_vDjbM2JKk8Ojkt-6Uj_fdn_NQPdzHeQnn0Y/view). Used the `curl` based install from a `ubuntu:latest` docker image interactively. Got the following output:

![image](https://user-images.githubusercontent.com/6568866/144297137-a2c7ed59-1de3-4194-af20-01482267f932.png)

I tried without the `/view` portion of the URL with the same result. Likewise, attempting to repeat the download results in the tool indicating that a partial download was detected, but it still fails.

**Comment by Akianonymus** [comment]
Hmm, seems to be a problem with documents, the api doesn't give the file size, will look into it.

**Comment by Akianonymus** [comment]
This should be fixed now, also added support for downloading in different formats, like pdf, etf, docx, html, etc.

Flag is `-df` or `--document-format`.
