### ISSUE TITLE
[Feature] Batch Downloading

### ISSUE THREAD

**Issue by shinji257** [Akianonymus/gdrive-downloader#36]
Is it possible to implement a batch downloading feature where I could supply it with a file containing a bunch of urls and it would download all of them?  Currently I just create a shell script that launches a new instance for the next file but batch downloading could offer up the ability to parallel download the files as well.

**Comment by shinji257** [comment]
Nevermind.  I'll leave this open just in case, but I see you can just pass multiple URLs and I'm an idiot for not noticing that before.

**Comment by Akianonymus** [comment]
Yeah multiple urls are allowed, but those are not processed parallely.

The readme is not very readable to be honest, maybe i need to seperate some stuff.
