### ISSUE TITLE
Incomplete download - Virus check

### ISSUE THREAD

**Issue by jrleyva** [Akianonymus/gdrive-downloader#37]
Hi,
Thank u for this great repository. Im having some troubles, after multiple succeeded files downloaded, next files are showing "Incomplete download ", trying via browser everything is ok but the files with incomplete download have virus check message.

This is a file example: https://drive.google.com/file/d/1nFpz6XlUZ9yIFSQmK0FAhXslkZazxjSE/ 

![Captura de Pantalla 2022-03-04 a la(s) 21 05 58](https://user-images.githubusercontent.com/19674861/156863507-ffddb7f6-041f-472d-8594-adeee15b04fb.png)

![Captura de Pantalla 2022-03-04 a la(s) 19 32 27](https://user-images.githubusercontent.com/19674861/156859445-7da7ec83-2b75-40b3-9805-ade6f37f91e5.png)

Hope can help me to solve the issue.  Thanks!

**Comment by Akianonymus** [comment]
This should be fixed now, update with `gdl -u` and try.

**Comment by Akianonymus** [comment]
This should be fixed, update with `gdl -u` and try.

**Comment by Tailslide** [comment]
Getting something like this too but with this message after 32 files downloaded:

```
your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.
```

**Comment by Akianonymus** [comment]
Well, that's normal

Are you still able to download without any authentication from browser ?

If yes, this maybe bypassable, or maybe just need to delay between the requests or something.

**Comment by Tailslide** [comment]
Ahh ok I just read the part about OAUTH authentication.. seems to be working after that.
I did get one failed that was bigger than 350Mb I think because when you get it interactively it gives you a warning about virus.

**Comment by Akianonymus** [comment]
Try specifying `-k` flag to use key to download ( it will use the internal key ), probably will do few more downloads before google blocks again.

A full proof solution is obviously to setup authentication, but again that's a hassle to setup for the first time. But i recommend you to set it up if you are frequently downloading from google drive, google anti spam is almost negligible there.

**Comment by Akianonymus** [comment]
> Ahh ok I just read the part about OAUTH authentication.. seems to be working after that. I did get one failed that was bigger than 350Mb I think because when you get it interactively it gives you a warning about virus.

The virus warnings are handled properly, every files above 100 mb gives the warning. It appeared because of the previous requests.

**Comment by Tailslide** [comment]
You're right!  It's working great. I ran into another issue but I'll open a new one for that.
