### ISSUE TITLE
Stops at 1000 items

### ISSUE THREAD

**Issue by Tailslide** [Akianonymus/gdrive-downloader#38]
Hi, I am downloading from a shared folder but it only finds the first 1000 items exactly and downloads them with no problem.

Is there some way to increase this limit?

**Comment by Tailslide** [comment]
Update.. if I change your code to page size 600 instead of 1000 it seems to be working ok. Maybe some bash variable limit is getting exceeded or something?

**Comment by Akianonymus** [comment]
I haven't set any limit, it actually fetches the 1000 items initially and then repeat the process until all the files and folders are found.

Dunno why 600 would work instead of 1000.

Do you have a sample link on which it was failing ?

**Comment by Tailslide** [comment]
Sure .. I pasted the command I was running here: https://cl1p.net/errsample

**Comment by Tailslide** [comment]
Ooops.. try again now:
https://cl1p.net/errsample

**Comment by Akianonymus** [comment]
![image](https://user-images.githubusercontent.com/32216346/157094422-bc42954e-507f-457f-acbc-cbde16cf9e6e.png)

Update and try, should be fixed.
