### ISSUE TITLE
cannot work with large files

### ISSUE THREAD

**Issue by 362227** [Akianonymus/gdrive-downloader#41]
https://drive.google.com/u/0/uc?id=1MR7M-as-stOIog2EyhNXwnKKC9-aXXiM

https://drive.google.com/u/0/uc?id=1MR7M-as-stOIog2EyhNXwnKKC9-aXXiM&export=download&confirm=t

**Comment by Akianonymus** [comment]
Seems like this file needs authentication, public downloads are not possible.

Atleast not working here, without an account login, not working in the browser too.

But otherwise, works in gdl with --oauth option.
