### ISSUE TITLE
Attempting to use gdl currently results in an empty folder

### ISSUE THREAD

**Issue by ElonSatoshi** [Akianonymus/gdrive-downloader#46]
For example, this one:

`gdl "https://drive.google.com/drive/folders/18NcDYyhr9BHAWZww1QAnCXCiqiPOQ1WJ"`

will result in an empty folder:

```
======================================[ Street Epistemology Tip Sheets | Empty Folder ]=======================================

========================================== Time Elapsed: 0 minute(s) and 1 seconds. ==========================================
```

**Comment by ichiKD** [comment]
SAME PROBLEM
$ gdl https://drive.google.com/drive/u/1/folders/1sn-F2y7JvG55HHGftSgF3ut3pjI-2PZJ -o
===================================================== Account: xxx =====================================================
==============================================[ ota quiz2 | Empty Folder ]==============================================
======================================= Time Elapsed: 0 minute(s) and 3 seconds. ======

**Comment by ichiKD** [comment]
Aight got it working you just add the below flag
` --key default="your api key"`

**Comment by ichiKD** [comment]
@ElonSatoshi 
> Aight got it working you just add the below flag ` --key default="your api key"`

**Comment by Akianonymus** [comment]
Check now, it should be fixed.
