### ISSUE TITLE
Implement A Proper Progress Bar

### ISSUE THREAD

**Issue by WinFan3672** [Akianonymus/gdrive-downloader#51]
I applaud your work in making Google Drive more usable and anonymous, but the current progress indicator is really bad. Because it continually scrolls, it can be difficult to watch the progress of the transfer without getting a migraine. One way of doing this is to use carriage returns alongside a progress bar. 

Here's an example Bash function that can do this (courtesy of ChatGPT because I can't do bash):

```
displayProgressBar() {
    local width=50
    local progress=$1
    local percentage=$((progress * 100 / 100))
    local fill=$((progress * width / 100))
    local progressBar="["
    for ((i = 0; i < width; i++)); do
        if [ "$i" -lt "$fill" ]; then
            progressBar+="="
        else
            progressBar+=" "
        fi
    done
    progressBar+="] $percentage%"
    echo -ne "$progressBar\r"
}
```

**Comment by Akianonymus** [comment]
It shouldn't scroll, something is wrong then.

And it does uses \r for progress.
